import React, {Component} from 'react';
import axios from '../../axios-orders';
import Order from "../../components/Order/Order";
import withErrorHandler from "../../hoc/withErrorHandler/withErrorHandler";

class Orders extends Component {
    state = {
        orders: [],
        loading: true
    };

    componentDidMount() {
        axios.get('/orders.json')
            .then(res => {
                // res.data is an object holding all the orders
                // its keys are uniquely generated by firebase
                const orders = Object.keys(res.data).map(key => {
                    return {
                        ...res.data[key],
                        id: key
                    };
                });
                console.log(orders);

                this.setState({
                    loading: false
                });
            })
            .catch(err => {
                this.setState({
                    loading: false
                })
            })
    }

    render() {
        return (
            <div>
                <Order />
                <Order />
            </div>
        );
    }
}

export default withErrorHandler(Orders, axios);